### ISSUE TITLE
注解方式跟@ResponseBody冲突

### ISSUE THREAD

**Issue by 2shui** [gaoice/easyexcel-spring-boot-starter#1]
习惯性加了@RestController，然后ResponseExcelReturnValueHandler implements HandlerMethodReturnValueHandler没执行

**Comment by gaoice** [comment]
使用 @ RestController 或者 @ ResponseBody 都会导致没执行。这和 HandlerMethodReturnValueHandler 放入的顺序有关，大多数情况都是要用 Spring 的 Handler，第三方的 Handler 放在 Spring 的 Handler 后面主要为了避免不必要的条件判断。
