### ISSUE TITLE
关于List对象下还有List的写法

### ISSUE THREAD

**Issue by lakuhana** [gaoice/easyexcel-spring-boot-starter#3]
public class OrdersExport {
    private Integer ordNumber;
    private String nickname;
    private List<CoExport> coExportList;
    private Double ordTotalMoney;
    private String sbiStoreName;
}

OrdersExport这个Bean下还有一个List<CoExport>的对象，不知道在classFieldNames中是如何获取？coExportList[0].name 这样的写法报异NoSuchFieldException

**Comment by blossom-x** [comment]
同样的SheetInfo也需要实现序列化接口呢

**Comment by gaoice** [comment]
对于集合类，可以编写一个 [Converter](https://github.com/gaoice/easyexcel/blob/master/src/main/java/com/gaoice/easyexcel/data/Converter.java) 进行处理，[使用示例](https://github.com/gaoice/easyexcel/blob/master/src/test/java/com/gaoice/easyexcel/test/ExcelBuilderTest.java#L101)。
