### ISSUE TITLE
用postman测试一直下载都是response.json？

### ISSUE THREAD

**Issue by liuchenyang0515** [gaoice/easyexcel-spring-boot-starter#4]
这个老是下载json文件？不是excel吗

**Comment by liuchenyang0515** [comment]
用法局限啊，现在都是@RestController，在项目中不通用

**Comment by gaoice** [comment]
2.1 版本提升了优先级，现在和 @RestController 或 @ResponseBody 同时使用的情况下会优先处理生成 excel 文件。
